version: '3'

services:
  
  db:
    restart: always
    container_name: blog_db_1
    image: mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=userdb
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3302:3306"
    networks:
      - db-net

  django:
    restart: always
    container_name: blog_backend_1
    image: myapp
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

